version: '3'

services:
  kspw-web:
    build:
      context: ./kspw-web
      args:
        - ENVIRONMENT=${ENV}
    image: kspw_web
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./kspw-web/cron:/home/cron
    links:
      - kspw-db
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - JWT_SECRET
      - RECAPTCHA_SECRET
      - ENV
    container_name: kspw-web

  kspw-db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./kspw-db/initialize:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    container_name: kspw-db

  kspw-cron:
    build: 
      context: ./kspw-cron
      args:
        - OAUTH_ACCESS_TOKEN=${OAUTH_ACCESS_TOKEN}
    image: kspw-cron
    restart: unless-stopped
    volumes:
      - ./kspw-cron/db-backups:/home/backups
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - OAUTH_ACCESS_TOKEN
      - ENV
    container_name: kspw-cron

  kspw-pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    links:
        - kspw-db:db
    ports:
        - 8080:80
    container_name: kspw-pma
