version: '3'

services:
  kspw-web:
    build:
      context: ./kspw-web
      args:
        - environment=${ENV}
    image: kspw_web
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    links:
      - kspw-db
    volumes:
      - ./kspw-web/cron:/etc/cron.d
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - JWT_SECRET
      - RECAPTCHA_SECRET
      - ENV
    container_name: kspw-web

  kspw-db:
    build: ./kspw-db
    image: kspw_db
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ../.env:/etc/environment
      - ./kspw-db/database/backups:/home/backups
      - ./kspw-db/database/initialize:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - OAUTH_ACCESS_TOKEN
      - ENV
    container_name: kspw-db    

  kspw-pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    links:
        - kspw-db:db
    ports:
        - 8080:80
    container_name: kspw-pma
