version: '3'

services:
  kspw-web:
    build: ./kspw-web
    image: kspw_web
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    links:
      - kspw-db
    volumes:
      - ../kellenschmidt.com/public:/var/www/kellenschmidt.com/public
      - ../api.kellenschmidt.com:/var/www/api.kellenschmidt.com
      - ../urlshortenerphp.kellenschmidt.com:/var/www/urlshortenerphp.kellenschmidt.com
      - ../test.kellenschmidt.com/public:/var/www/test.kellenschmidt.com/public
      - ../testapi.kellenschmidt.com:/var/www/testapi.kellenschmidt.com
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - JWT_SECRET
      - RECAPTCHA_SECRET
      - ENV
    container_name: kspw-web

  kspw-db:
    build: ./kspw-db
    image: kspw_db
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ../database/data:/var/lib/mysql
      # - ../database/schema_only:/docker-entrypoint-initdb.d
      - ../database/schema_with_data:/docker-entrypoint-initdb.d
      - ../database/backups:/home/db-backups
      - ../.env:/etc/environment
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - OAUTH_ACCESS_TOKEN
    container_name: kspw-db    

  kspw-pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    links:
        - kspw-db:db
    ports:
        - 8000:80
    container_name: kspw-pma
